name: Merge Four Gospels

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Increment version and push
      run: |
        perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Jake Hadley
        author_email: jakehadley10@gmail.com
        message: 'Increment version number'
        add: '*.yaml'
