name: Verify Four Gospels

on: [pull_request]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - name: Set up onepub
        run: |
          flutter pub global activate onepub
          export ONEPUB_TOKEN="${{ secrets.ONEPUB_T }}"; onepub import
      - name: Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good packages get --recursive --ignore="!*"
        shell: bash

      - name: Check Formatting
        run: dart format --line-length '80' --set-exit-if-changed lib test
        shell: bash

      - name: Analyze
        run: flutter analyze lib test
        shell: bash

      - name: Run Tests
        run: very_good test -j '4' --optimization --coverage --test-randomize-ordering-seed random
        shell: bash

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: ./coverage/lcov.info
          exclude: ''
          min_coverage: 0
      
      - name: Increment version
        run: |
          perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Jake Hadley
          author_email: jakehadley10@gmail.com
          message: 'Increment version number'
          add: '*.yaml'
